import type { Metadata } from "next";
import localFont from "next/font/local";
import SideBar from "@/components/SideBar";
;
import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import Navbar from "@/components/navbar";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Root2Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    if (cookies().get("token") == undefined) {
        redirect("/")
    }
    else {
        return (
            <html lang="en">
                <SideBar />
                <Navbar />
                <body
                    className={`${geistSans.variable} ${geistMono.variable} bg-gray-50 antialiased`}
                >
                    {children}
                </body>
            </html>
        );
    }
}
